config/routes.rb
BusinessCard::Application.routes.draw do
  devise_for :users
  resources :companies do
    resources :groups do
      resources :users do
        resources :name_cards
      end
    end
  end
  root :to => "companies#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  paginates_per 10
  has_many :groups, :dependent => :destroy
  validates :name, presence: true, length: { maximum: 6 }
  validates :url, presence: true, length: { maximum: 30 }, format: URI.regexp(['http', 'https'])
  validates :address, presence: true, length: { maximum: 18 }
  validates :tel, :fax, presence: true, format: { with: /\A[0-9]{1,4}-[0-9]{1,4}-[0-9]{4}\z/ }
  validates :tel, presence: true, length: { maximum: 13 }
  validates :fax, presence: true, length: { maximum: 13 }
end

app/models/group.rb
class Group < ActiveRecord::Base
  paginates_per 10
  belongs_to :company
  has_many :users, :dependent => :destroy

  validates :name, presence: true, length: {maximum: AVAILABLE_SHORT_STRING_LENGTH}
end

app/models/name_card.rb
class NameCard < ActiveRecord::Base
  paginates_per 10
  belongs_to :user

  validates :name, presence: true, length: {maximum: AVAILABLE_TEXT_LENGTH}
  validates :address, presence: true, length: {maximum: AVAILABLE_LONG_STRING_LENGTH}
  validates :url, presence: true, length: {maximum: 30}, format: URI.regexp(['http', 'https'])
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :fax, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  paginates_per 10
  belongs_to :group
  has_many :name_cards, :dependent => :destroy

  SHORT_LENGTH = 5
  validates :name, presence: true, length: {maximum: AVAILABLE_TEXT_LENGTH}
  validates :tel, format: {with: /\A[0-9]{2,4}-[0-9]{2,4}-[0-9]{4}\Z/}
  validates :mail, length: {maximum: AVAILABLE_TEXT_LENGTH, minimun: MAIL_ADDRESS_SHORT_LENGTH }, allow_blank: false, allow_nil: false,
    uniqueness: true, format: {with: /\A[A-Z0-9%\.\_\-\+]*@((?:[-a-z0-9]+.)+[a-z]{2,})\Z/i}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_company
    company_id = params[:company_id] ? params[:company_id] : params[:id]
    @company = Company.find(company_id)
  end

  def  set_group
    group_id = params[:group_id] ? params[:group_id] : params[:id]
    @group = Group.find(group_id)
  end

  def set_user
    user_id = params[:user_id] ? params[:user_id] : params[:id]
    @user = User.find(user_id)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    #@companies = Company.all
    @companies = Company.limit(10).order(:name).page(params[:page])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    redirect_to companies_url
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

    def company_params
      params.require(:company).permit(:name, :address, :tel, :fax, :url)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_company
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @company = Company.find(params[:company_id])
    @group = @company.groups.new
    @groups = @company.groups.order(:name).page(params[:page])
  end

  def show
  end

  def new
    #company = Company.find(params[:company_id])
    @group = @company.groups.new
  end

  def create
    #company = Company.find(params[:company_id])
    @group = @company.groups.new(group_params)
    if @group.save
      #redirect_to company_groups_path(params[:company_id]), notice: 'Group was successfully updated.'
      redirect_to company_groups_path(@group.company_id, @group.id), notice: 'Group was successfully updated.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to company_group_path(@group.company_id,@group.id), notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to company_groups_path(params[:company_id])
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/name_cards_controller.rb
class NameCardsController < ApplicationController
  before_action :set_user
  before_action :set_name_card, only: [:show, :edit, :update, :destroy]

  def index
    user = User.find(params[:user_id])
    @name_cards = user.name_cards.order(:name).page(params[:page])
  end

  def show
  end

  def new
    user = User.find(params[:user_id])
    @name_card = user.name_cards.new
  end

  def create
    user = User.find(params[:user_id])
    @name_card = user.name_cards.create(name_card_params)
    if @name_card.save
      redirect_to company_group_users_path(user.group_id, user.id), notice: 'Group was successfully updated.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @name_card.update(name_card_params)
      redirect_to company_group_user_path(@name_card.user.group.company_id, @name_card.user.group.id, @name_card.user.id, @name_card.id) , notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @name_card.destroy
    redirect_to company_group_users_path(@name_card.user.group.company_id, @name_card.user.group.id, @name_card.user.id, @name_card.id)
  end

  private

  def set_name_card
    @name_card = NameCard.find(params[:id])
  end

  def name_card_params
    params.require(:name_card).permit(:name, :address, :fax, :tel, :url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_group
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @group = Group.find(params[:group_id])
    @user = @group.users.new
    @users = @group.users.order(:name).page(params[:page])
  end

  def show
  end

  def new
    #group = Group.find(params[:group_id])
    @user = @group.users.new
  end

  def create
    #group = Group.find(params[:group_id])
    @user = @group.users.create(user_params)
    if @user.save
      redirect_to company_group_users_path(@group.company_id, @group.id), notice: 'Group was successfully updated.'
      #redirect_to company_group_users_path(params[:group_id]), notice: 'Group was successfully updated.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to company_group_user_path(@user.group.company_id,@user.group.id,@user.id) , notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user.destroy
    #redirect_to company_group_users_path(@user.group.company_id,@user.group.id)
    redirect_to company_group_users_path(params[:group_id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :mail, :tel)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/helpers/name_card_helper.rb
module NameCardHelper
end

app/helpers/name_cards_helper.rb
module NameCardsHelper
end

app/helpers/scaffold_tests_helper.rb
module ScaffoldTestsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Tel</th>
      <th>Fax</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.address %></td>
        <td><%= company.tel %></td>
        <td><%= company.fax %></td>
        <td><%= company.url %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @companies %>
<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @company.tel %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @company.fax %>
</p>

<p>
  <strong>Url:</strong>
  <%= @company.url %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>
<%= link_to 'go to group', company_groups_path(company_id: @company.id) %>

app/views/groups/_form.html.erb
<%= form_for @group, :url => {:action => params[:action] == 'new' ? 'create' : (params[:action] == 'edit') ? 'update' : 'create'} do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', company_groups_path %>
<%= link_to 'Back', company_groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td>
        <td><%= link_to group.name, company_group_path(@company, group) %></td>
        <td><%= link_to 'Show', company_group_path(@company, group) %></td>
        <td><%= link_to 'Edit', edit_company_group_path(@company, group) %></td>
        <td><%= link_to 'Destroy', company_group_path(@company, group), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @groups %>
<%= link_to 'New Group', new_company_group_path %>
<%= link_to 'Back', companies_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%#= link_to 'Back', company_groups_path(@group.company_id) %>
<%= link_to 'Back', company_groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>


<%= link_to 'Edit', edit_company_group_path %> |
<%= link_to 'Back', company_groups_path %>
<%= link_to 'go to users', company_group_users_path(group_id: @group.id) %>

app/views/hoges/_form.html.erb
<%= form_for(@hoge) do |f| %>
  <% if @hoge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hoge.errors.count, "error") %> prohibited this hoge from being saved:</h2>

      <ul>
      <% @hoge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :suuji %><br>
    <%= f.number_field :suuji %>
  </div>
  <div class="field">
    <%= f.label :mojiretsu %><br>
    <%= f.text_field :mojiretsu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hoges/edit.html.erb
<h1>Editing hoge</h1>

<%= render 'form' %>

<%= link_to 'Show', @hoge %> |
<%= link_to 'Back', hoges_path %>

app/views/hoges/index.html.erb
<h1>Listing hoges</h1>

<table>
  <thead>
    <tr>
      <th>Suuji</th>
      <th>Mojiretsu</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hoges.each do |hoge| %>
      <tr>
        <td><%= hoge.suuji %></td>
        <td><%= hoge.mojiretsu %></td>
        <td><%= link_to 'Show', hoge %></td>
        <td><%= link_to 'Edit', edit_hoge_path(hoge) %></td>
        <td><%= link_to 'Destroy', hoge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoge', new_hoge_path %>

app/views/hoges/new.html.erb
<h1>New hoge</h1>

<%= render 'form' %>

<%= link_to 'Back', hoges_path %>

app/views/hoges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suuji:</strong>
  <%= @hoge.suuji %>
</p>

<p>
  <strong>Mojiretsu:</strong>
  <%= @hoge.mojiretsu %>
</p>

<%= link_to 'Edit', edit_hoge_path(@hoge) %> |
<%= link_to 'Back', hoges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessCard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<header>
  <nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %> 
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/name_cards/_form.html.erb
<%= form_for @name_card, :url => {:action => params[:action] ==  'new' ? 'create' : (params[:action] == 'edit') ? 'update' : 'create' } do |f| %>
  <% if @name_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name_card.errors.count, "error") %> prohibited this name_card from being saved:</h2>

      <ul>
      <% @name_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/name_cards/edit.html.erb
<h1>Editing name_card</h1>

<%= render 'form' %>

<%= link_to 'Show', company_group_user_name_card_path %> |
<%= link_to 'Back', company_group_user_name_cards_path %>

app/views/name_cards/index.html.erb
<h1>Listing name_cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Tel</th>
      <th>Fax</th>
      <th>Url</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @name_cards.each do |name_card| %>
      <tr>
        <td><%= name_card.name %></td>
        <td><%= name_card.address %></td>
        <td><%= name_card.tel %></td>
        <td><%= name_card.fax %></td>
        <td><%= name_card.url %></td>
        <td>
          <%= link_to 'Show', company_group_user_name_card_path(name_card.user.group.company_id, name_card.user.group_id, name_card.user.id, name_card.id) %><br />
          <%= link_to 'Edit', edit_company_group_user_name_card_path(name_card.user.group.company_id, name_card.user.group_id, name_card.user.id, name_card.id) %><br />
          <%= link_to 'Destroy', company_group_user_name_card_path(name_card.user.group.company_id, name_card.user.group_id, name_card.user.id, name_card.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @name_cards %>
<%= link_to 'New name_card', new_company_group_user_name_card_path %>
<%= link_to 'Back', company_group_users_path %>

app/views/name_cards/new.html.erb
<h1>New name_card</h1>

<%= render 'form' %>

<%= link_to 'Back', company_group_user_name_cards_path %>

app/views/name_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @name_card.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @name_card.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @name_card.tel %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @name_card.fax %>
</p>

<p>
  <strong>Url:</strong>
  <%= @name_card.url %>
</p>

<%= link_to 'Edit', edit_company_group_user_name_card_path %> |
<%= link_to 'Back', company_group_users_path %>

app/views/users/_form.html.erb
  <%= form_for @user, :url => {:action => params[:action] == 'new' ? 'create' : (params[:action] == 'edit') ? 'update' : 'create'} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', company_group_user_path %> |
<%= link_to 'Back', company_group_users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Tel</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.mail %></td>
        <td><%= user.tel %></td>
        <td>
          <%= link_to 'Show', company_group_user_path(user.group.company_id, user.group_id, user.id) %><br />
          <%= link_to 'Edit', edit_company_group_user_path(user.group.company_id, user.group_id, user.id) %><br />
          <%= link_to 'Destroy', company_group_path(user.group.company_id, user.group_id, user.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @users %>
<%= link_to 'New User', new_company_group_user_path %>
<%= link_to 'Back', company_groups_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%#= link_to 'Back', company_group_users_path(@user.group_id) %>
<%= link_to 'Back', company_group_users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user.tel %>
</p>

<%= link_to 'Edit', edit_company_group_user_path %> |
<%= link_to 'Back', company_groups_path %>
<%= link_to 'go to users', company_group_users_path(user_id: @user.id) %>